import {
  LayoutDashboard,
  Shield,
  CalendarDays,
  UserCheck,
  Dumbbell,
  TableProperties,
  MessageSquare,
  Landmark,
  Upload,
  ShieldAlert,
  Settings,
  Info,
  UserCircle,
  Calendar,
  Users,
  Bell,
  Lock,
} from 'lucide-react';
import { MODULE_LABELS_DE } from '@/constants/uiLabels';
import type { RouteConfig } from '@/types/navigation';

export const ROUTES: RouteConfig[] = [
  {
    path: '/',
    label: MODULE_LABELS_DE.dashboard,
    moduleKey: 'dashboard',
    icon: LayoutDashboard,
    group: 'sport',
    navVisibility: 'sidebar',
    exact: true,
    guard: { type: 'authenticated' },
  },
  {
    path: '/mitglieder',
    label: MODULE_LABELS_DE.members,
    moduleKey: 'members',
    icon: Users,
    group: 'club',
    navVisibility: 'sidebar',
    guard: { type: 'permission', permission: 'member:read' },
  },
  {
    path: '/mannschaften',
    label: MODULE_LABELS_DE.teams,
    moduleKey: 'teams',
    icon: Shield,
    group: 'sport',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'teams', level: 'READ' },
  },
  {
    path: '/spielplan',
    label: MODULE_LABELS_DE.schedule,
    moduleKey: 'schedule',
    icon: CalendarDays,
    group: 'sport',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'schedule', level: 'READ' },
  },
  {
    path: '/ersatzstellung',
    label: MODULE_LABELS_DE.substitutes,
    moduleKey: 'substitutes',
    icon: UserCheck,
    group: 'sport',
    navVisibility: 'sidebar',
    guard: { type: 'permission', permission: 'substitute:read' },
  },
  {
    path: '/training',
    label: MODULE_LABELS_DE.training,
    moduleKey: 'training',
    icon: Dumbbell,
    group: 'sport',
    navVisibility: 'sidebar',
    guard: { type: 'permission', permission: 'training:read' },
  },
  {
    path: '/tabelle',
    label: MODULE_LABELS_DE.standings,
    moduleKey: 'standings',
    icon: TableProperties,
    group: 'sport',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'standings', level: 'READ' },
  },
  {
    path: '/kommunikation',
    label: MODULE_LABELS_DE.communication,
    moduleKey: 'communication',
    icon: MessageSquare,
    group: 'club',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'communication', level: 'READ' },
  },
  {
    path: '/vorstand',
    label: MODULE_LABELS_DE.board,
    moduleKey: 'board',
    icon: Landmark,
    group: 'club',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'board', level: 'READ' },
  },
  {
    path: '/admin',
    label: MODULE_LABELS_DE.admin,
    moduleKey: 'admin',
    icon: ShieldAlert,
    group: 'system',
    navVisibility: 'sidebar',
    guard: { type: 'roles', roles: ['admin', 'developer'] },
  },
  {
    path: '/saisons',
    label: MODULE_LABELS_DE.seasons,
    moduleKey: 'seasons',
    icon: Calendar,
    group: 'system',
    navVisibility: 'sidebar',
    guard: { type: 'roles', roles: ['admin', 'developer'] },
  },
  {
    path: '/einstellungen',
    label: MODULE_LABELS_DE.settings,
    moduleKey: 'settings',
    icon: Settings,
    group: 'system',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'settings', level: 'READ' },
  },
  {
    path: '/import',
    label: MODULE_LABELS_DE.import,
    moduleKey: 'import',
    icon: Upload,
    group: 'system',
    navVisibility: 'sidebar',
    guard: { type: 'module', module: 'import', level: 'READ' },
  },
  {
    path: '/sicherheit',
    label: MODULE_LABELS_DE.security,
    moduleKey: 'security',
    icon: Lock,
    group: 'personal',
    navVisibility: 'sidebar',
    guard: { type: 'authenticated' },
  },
  {
    path: '/benachrichtigungen',
    label: MODULE_LABELS_DE.notifications,
    moduleKey: 'notifications',
    icon: Bell,
    group: 'personal',
    navVisibility: 'sidebar',
    guard: { type: 'authenticated' },
  },
  {
    path: '/datenschutz',
    label: MODULE_LABELS_DE.privacy,
    moduleKey: 'privacy',
    icon: Lock,
    group: 'personal',
    navVisibility: 'sidebar',
    guard: { type: 'authenticated' },
  },
  {
    path: '/info',
    label: MODULE_LABELS_DE.info,
    moduleKey: 'info',
    icon: Info,
    group: 'personal',
    navVisibility: 'sidebar',
    guard: { type: 'authenticated' },
  },
  {
    path: '/profil',
    label: MODULE_LABELS_DE.profile,
    moduleKey: 'profile',
    icon: UserCircle,
    group: 'personal',
    navVisibility: 'hidden',
    guard: { type: 'authenticated' },
  },
  {
    path: '/login',
    label: MODULE_LABELS_DE.auth,
    moduleKey: 'auth',
    group: 'system',
    navVisibility: 'hidden',
    guard: { type: 'public' },
  },
];
