import type { AppRole } from '@/types/auth';

export const PERMISSION_LEVELS = ['NONE', 'READ', 'WRITE'] as const;
export type PermissionLevel = (typeof PERMISSION_LEVELS)[number];

export const MODULE_KEYS = [
  'dashboard',
  'teams',
  'schedule',
  'members',
  'communication',
  'board',
  'settings',
  'import',
  'substitutes',
  'training',
  'standings',
  'security',
  'notifications',
  'privacy',
  'info',
  'seasons',
] as const;

export type ModuleKey = (typeof MODULE_KEYS)[number];

export const SYSTEM_APP_ROLES: readonly AppRole[] = [
  'developer',
  'admin',
  'vorstand',
  'trainer',
  'spieler',
  'mitglied',
  'fördermitglied',
] as const;

export const isPermissionLevel = (value: string): value is PermissionLevel =>
  (PERMISSION_LEVELS as readonly string[]).includes(value);

export const isModuleKey = (value: string): value is ModuleKey =>
  (MODULE_KEYS as readonly string[]).includes(value);

export const SYSTEM_APP_ROLE_PERMISSIONS: Record<string, Record<ModuleKey, PermissionLevel>> = {
  developer: {
    dashboard: 'WRITE',
    teams: 'WRITE',
    schedule: 'WRITE',
    members: 'WRITE',
    communication: 'WRITE',
    board: 'WRITE',
    settings: 'WRITE',
    import: 'WRITE',
    substitutes: 'WRITE',
    training: 'WRITE',
    standings: 'WRITE',
    security: 'WRITE',
    notifications: 'WRITE',
    privacy: 'WRITE',
    info: 'WRITE',
  },
  admin: {
    dashboard: 'WRITE',
    teams: 'WRITE',
    schedule: 'WRITE',
    members: 'WRITE',
    communication: 'WRITE',
    board: 'WRITE',
    settings: 'WRITE',
    import: 'WRITE',
    substitutes: 'WRITE',
    training: 'WRITE',
    standings: 'WRITE',
    security: 'WRITE',
    notifications: 'WRITE',
    privacy: 'WRITE',
    info: 'WRITE',
  },
  vorstand: {
    dashboard: 'READ',
    teams: 'WRITE',
    schedule: 'WRITE',
    members: 'WRITE',
    communication: 'WRITE',
    board: 'WRITE',
    settings: 'WRITE',
    import: 'READ',
    substitutes: 'WRITE',
    training: 'WRITE',
    standings: 'READ',
    security: 'READ',
    notifications: 'READ',
    privacy: 'READ',
    info: 'READ',
  },
  trainer: {
    dashboard: 'READ',
    teams: 'WRITE',
    schedule: 'WRITE',
    members: 'READ',
    communication: 'READ',
    board: 'NONE',
    settings: 'NONE',
    import: 'NONE',
    substitutes: 'WRITE',
    training: 'WRITE',
    standings: 'READ',
    security: 'NONE',
    notifications: 'READ',
    privacy: 'NONE',
    info: 'READ',
  },
  spieler: {
    dashboard: 'READ',
    teams: 'READ',
    schedule: 'READ',
    members: 'READ',
    communication: 'READ',
    board: 'NONE',
    settings: 'NONE',
    import: 'NONE',
    substitutes: 'READ',
    training: 'READ',
    standings: 'READ',
    security: 'NONE',
    notifications: 'READ',
    privacy: 'NONE',
    info: 'READ',
  },
  mitglied: {
    dashboard: 'READ',
    teams: 'READ',
    schedule: 'READ',
    members: 'READ',
    communication: 'NONE',
    board: 'NONE',
    settings: 'NONE',
    import: 'NONE',
    substitutes: 'NONE',
    training: 'READ',
    standings: 'READ',
    security: 'NONE',
    notifications: 'READ',
    privacy: 'NONE',
    info: 'READ',
  },
  fördermitglied: {
    dashboard: 'READ',
    teams: 'READ',
    schedule: 'READ',
    members: 'READ',
    communication: 'NONE',
    board: 'NONE',
    settings: 'NONE',
    import: 'NONE',
    substitutes: 'NONE',
    training: 'NONE',
    standings: 'READ',
    security: 'NONE',
    notifications: 'NONE',
    privacy: 'NONE',
    info: 'READ',
  },
};
