// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-teams.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-teams.ts
var list_teams_default = defineTool({
  name: "list_teams",
  title: "List teams",
  description: "List the club's teams (name, age group, league, division, size). Only active teams unless include_inactive is true.",
  inputSchema: {
    include_inactive: z.boolean().optional().describe("Include inactive teams (default false)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("teams").select("id, name, age_group, league, division, team_size, is_active, clicktt_url").order("name").limit(limit ?? 100);
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    return error ? errorResult(error.message) : jsonResult(data);
  }
});

// src/lib/mcp/tools/list-members.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_members_default = defineTool2({
  name: "list_members",
  title: "List members",
  description: "List club members with basic contact info and TTR/QTTR rating. Optional case-insensitive name search.",
  inputSchema: {
    search: z2.string().trim().optional().describe("Name substring (matches first or last name, case-insensitive)."),
    include_inactive: z2.boolean().optional().describe("Include inactive members (default false)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, include_inactive, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("members").select(
      "id, first_name, last_name, email, age_group, gender, ttr_rating, qttr_rating, is_active"
    ).order("last_name").limit(limit ?? 50);
    if (!include_inactive) query = query.eq("is_active", true);
    if (search) query = query.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%`);
    const { data, error } = await query;
    return error ? errorResult(error.message) : jsonResult(data);
  }
});

// src/lib/mcp/tools/list-upcoming-matches.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_upcoming_matches_default = defineTool3({
  name: "list_upcoming_matches",
  title: "List upcoming matches",
  description: "List scheduled matches from today onwards, ordered by date. Optionally filter by team_id.",
  inputSchema: {
    team_id: z3.string().uuid().optional().describe("Restrict to a single team's matches."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ team_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let query = supabaseForUser(ctx).from("schedule_matches").select(
      "id, match_date, match_time, home_team, away_team, home_score, away_score, is_home, status, team_id"
    ).gte("match_date", today).order("match_date").limit(limit ?? 25);
    if (team_id) query = query.eq("team_id", team_id);
    const { data, error } = await query;
    return error ? errorResult(error.message) : jsonResult(data);
  }
});

// src/lib/mcp/tools/list-news.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_news_default = defineTool4({
  name: "list_news",
  title: "List news",
  description: "List the most recent published club news items.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("news").select("id, title, content, published_at, is_published").eq("is_published", true).order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    return error ? errorResult(error.message) : jsonResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "lgewnzeuusbtcbmozhnd";
var mcp_default = defineMcp({
  name: "tt-manager-pro-mcp",
  title: "TT-Manager Pro",
  version: "0.1.0",
  instructions: "Read-only tools for the TT-Manager Pro table tennis club app. Use these to look up teams, members, upcoming matches, and published news for the signed-in user's club.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_teams_default, list_members_default, list_upcoming_matches_default, list_news_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
